# Generated by Django 4.0.5 on 2022-06-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
