# Generated by Django 4.0.5 on 2022-06-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0004_featurew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
