# Generated by Django 4.0.5 on 2022-06-27 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0005_software'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Software',
            new_name='Soft',
        ),
    ]
